# Generated by Django 2.2 on 2019-04-04 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='samples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('views', models.IntegerField()),
                ('redViews', models.IntegerField()),
                ('estimatedMinutesWatched', models.IntegerField()),
                ('estimatedRedMinutesWatched', models.IntegerField()),
                ('averageViewDuration', models.IntegerField()),
                ('averageViewPercentage', models.FloatField()),
                ('subscribersGained', models.IntegerField()),
                ('subscribersLos', models.IntegerField()),
                ('comments', models.IntegerField()),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
                ('videosAddedToPlaylists', models.IntegerField()),
                ('videosRemovedFromPlaylists', models.IntegerField()),
                ('shares', models.IntegerField()),
            ],
        ),
    ]
